//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentContent
    {
        public int Id { get; set; }
        public System.Guid RowGuid { get; set; }
        public byte[] Data { get; set; }
    
        public virtual DocumentMeta DocumentMeta { get; set; }
    }
}
